import type { Metadata } from 'next';

import { Navbar } from '@/components/layout/Navbar';
import { Main } from '@/components/ui/main';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      <Main className="flex flex-col px-3 mt-8 mb-24 space-y-10 md:px-12">{children}</Main>
    </>
  );
}
