import type { Metadata } from 'next';

import { Main } from '@/components/ui/main';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return <Main className="h-screen px-3 space-y-10 md:px-12">{children}</Main>;
}
